name: Sanity check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  sanity-check:
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os:
          [ubuntu-latest, macos-latest, windows-latest, ubicloud-standard-2-arm]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
      - name: Run the install script
        id: install_linux
        timeout-minutes: 1
        if: matrix.os != 'windows-latest'
        run: |
          ./install-ctl.sh 
          PATH="${HOME}/.omnistrate/bin:${PATH}"
          ctl_version=$(omnistrate-ctl --version)
          echo "Omnistrate CTL version: $ctl_version"
          echo "ctl_version=$ctl_version" >> "$GITHUB_OUTPUT"

      - name: Run the binary (windows only)
        id: install_windows
        timeout-minutes: 1
        if: matrix.os == 'windows-latest'
        run: |
          ./install-ctl.sh
          Get-ChildItem $env:USERPROFILE -Force
          $ctl_version = & "$env:USERPROFILE\omnistrate-ctl.exe" --version
          Write-Host "Omnistrate CTL version: $ctl_version"
          "ctl_version=$ctl_version" >> $env:GITHUB_OUTPUT
