name: Sanity check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

env:
  GOPRIVATE: "github.com/omnistrate/*"
  GOPROXY: ${{ secrets.GOPROXY }}
  GOSUMDB: ${{ secrets.GOSUMDB }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # platforms to build the image for
  PLATFORMS: linux/arm64,linux/amd64
  # default platform of the runners, used to mitigate time of building on x arch during PRs
  PR_PLATFORMS: linux/amd64
  # name of the package
  PACKAGE_NAME: omnistrate-ctl

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  sanity-check:
    permissions:
      contents: read

    strategy:
      matrix:
        os:
          [ubuntu-latest, macos-latest, windows-latest, ubicloud-standard-2-arm]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Run the install script
        id: run_binary_linux
        timeout-minutes: 1
        if: matrix.os != 'windows-latest'
        run: |
          ./install-ctl.sh
          PATH="/root/.omnistrate/bin:${PATH}"
          ctl_version=$(omnistrate-ctl --version)
          echo "Omnistrate CTL version: $ctl_version"
          echo "ctl_version=$ctl_version" >> "$GITHUB_OUTPUT"

      - name: Run the binary (windows only)
        id: run_binary_windows
        timeout-minutes: 1
        if: matrix.os == 'windows-latest'
        run: |
          ./install-ctl.sh
          $ctl_version=omnistrate-ctl.exe --version
          echo "Omnistrate CTL version: $ctl_version"
          echo "ctl_version=$ctl_version" >> $env:GITHUB_OUTPUT
